#!/bin/bash

steps=(A B C D)

current_quality=$(iwconfig wlp3s0 | grep -i quality | sed 's/^.*\=\([0-9]*\)\/.*$/\1/')
max_quality=$(iwconfig wlp3s0 | grep -i quality | sed 's/^.*\/\([0-9]*\).*$/\1/')

perc=$((100 * current_quality/max_quality))

icon_index=$(printf "%.0f" $(( $(( 100 * $(( ${#steps[@]} - 1 ))/100 )) * $perc ))e-2)

echo "${steps[icon_index]} $perc%"
#printf "%s %d%%" $icon "$((100 * current_quality/max_quality))"


