#!/bin/bash

# Display the cpu temperature.

# require: lm_sensors

steps=(   )

temp=$(sensors | awk '/Core 0/ {print $3}' | sed 's/^\+\([0-9]*\).*/\1/')
icon_index=$(printf "%.0f" $(( $(( 100 * $(( ${#steps[@]} - 1 ))/100 )) * $temp ))e-2)

echo "${steps[icon_index]} $temp°C"
