#!/bin/sh

DMD="${1:-/mnt}"

SIZE_PADDING=$(lsblk -rpn -o SIZE | awk '{ printf "%s\n", length($1) }' | sort -r -n | head -1)
MODL_PADDING=$(lsblk -rn -o MODEL | awk '{ print length($1) }' | sort -nr | head -1)
NAME_PADDING=$(lsblk -rpn -o NAME | awk '{ printf "%s\n", length($1)+2 }' | sort -r -n | head -1)
# length($1)+2 for the quotes in the name variable below

usb() {
	lsblk -Ppn -o NAME,SIZE,LABEL,TYPE,UUID,MOUNTPOINT,VENDOR,MODEL | {
		while IFS= read -r line;
		do
			IFS='
			'
			set -- $(echo "$line" | sed 's/.*="\(.*\)" \+.*="\(.*\)" \+.*="\(.*\)" \+.*="\(.*\)" \+.*="\(.*\)" \+.*="\(.*\)" \+.*="\(.*\)" \+.*="\(.*\)"/"\1"\n"\2"\n"\3"\n"\4"\n"\5"\n"\6"\n"\7"\n"\8"/')

			_name="$(echo "$1" | sed 's/"\(.*\)"/\1/')"
			_size="$(echo "$2" | sed 's/"\(.*\)"/\1/')"
			_labl="$(echo "$3" | sed 's/"\(.*\)"/\1/')"
			_type="$(echo "$4" | sed 's/"\(.*\)"/\1/')"
			_uuid="$(echo "$5" | sed 's/"\(.*\)"/\1/')"
			_mntp="$(echo "$6" | sed 's/"\(.*\)"/\1/')"
			
			if [ "$_type" = "disk" ];
			then
				_vndr="$(echo "$7" | sed 's/"\(.*\)"/\1/;s/ *$//')"
				_modl="$(echo "$8" | sed 's/"\(.*\)"/\1/')"
			fi

			if [ -z "$_mntp" ];
			then
				if [ "$_type" != "disk" ] && [ -n "$_uuid" ] \
					|| [ "$_type" = "disk" ] \
					&& [ "$(lsblk "$_name" -rn -o NAME | wc -l)" -eq 1 ];
				then
					printf "%-*s - %-*s -> [%s] %-*s (%s)\n" \
						$SIZE_PADDING "$_size" \
						$NAME_PADDING "\"$_name\"" \
						"$_vndr" \
						$MODL_PADDING "$_modl" \
						"$_labl"
				fi
			fi
		done
	}
}

mnt_folders() {
	find "$DMD" -mindepth 1 -maxdepth 1 -type d -printf "%P\n" | {
		while IFS= read -r line;
		do
			if ! mountpoint -q -- "$DMD/$line";
			then
				printf "%s\n" "$line"
			fi
		done
	} | dmenu -p "Choose a mounting point (current dir: \"$DMD\")" -l 20
}

type=$(printf "USB\nANDROID" | dmenu -p "Select a device type to mount")
case "$type" in
	USB)
		mntp="$(usb | dmenu -p "Select a partition" -l 20)"
		part="$(echo "$mntp" | sed 's/[^"]*"\([^"]*\)".*/\1/')"
		
		[ -n "$part" ] && mnt_point=$(mnt_folders)

		if [ -n "$mnt_point" ];
		then
			[ ! -d "$DMD/$mnt_point" ] && sudo mkdir -p "$DMD/$mnt_point"
			sudo mount "$part" "$DMD/$mnt_point"
		fi
		;;
	ANDROID)
		mntd="$(simple-mtpfs -l 2>/dev/null | dmenu -p "Select a device" -l 20)"
		devno="$(echo "$mntd" | sed 's/\(^[0-9]*\):.*/\1/')"

		[ -n "$devno" ] && mnt_point=$(mnt_folders)

		if [ -n "$mnt_point" ];
		then
			[ ! -d "$DMD/$mnt_point" ] && sudo mkdir -p "$DMD/$mnt_point"
			sudo simple-mtpfs --device "$devno" "$DMD/$mnt_point" -o allow_other
		fi
		;;
esac
