#!/bin/sh

# backups dotfiles

die() {
	echo "$1"
	exit 1
}

[ -z "$1" ] && die "It's necessary to provide a directory for the backup."

dir=$(readlink -f "$1")

printf "%s\n" "Config files are going to be backed up."
printf "%s\n" "The chosen directory for the backup is: \"$dir\""
printf "\n%s" "wish to continue? (y/n)" ; read op
[ "$(printf $op | tr '[A-Z]' '[a-z]')" != "y" ] && exit 0

#cp "$HOME/.tmux.conf" "$dir" # tmux config file
cp "$HOME/.xinitrc" "$dir" # startx config file
cp "$HOME/.profile" "$dir" # path configs and other variable definitions
cp "$HOME/.xprofile" "$dir" # daemons to be run on startup 
#cp "$HOME/.zprofile" "$dir" # zsh startup config
cp "$HOME/.bashrc" "$dir" # bash startup config

cp -r "$HOME/.config" "$dir" # config files directory
