#!/bin/sh

# Install the programs that I mostly use

die() {
	echo "$1"
	exit
}

[ $(whoami) != "root" ] && die "must be root!"
[ -z "$1" ] && die "provide username!"
[ -z $(id -u "$1" 2>/dev/null) ] && die "username $1 doesn't exist!"

home="/home/$1" # $1 must be the username, to access the home directory

############################## Custom instalations ##############################
suckless() {
	suckless="dmenu; dmw; st; dmwblocks; slock; surf"

	mkdir $home/suckless ; cd $home/suckless
	
	for rep in ${suckless}; do
		git clone https://github.com/pvpscript/$rep
		cd $rep
		make
		make install
		cd ..
	done
}

nerd_fonts() {
	cd $home

	git clone https://github.com/ryanoasis/nerd-fonts
	cd nerd-fonts
	./install.sh DejaVuSansMono
	./install.sh Inconsolata
	./install.sh Overpass
	./install.sh Noto
	./install.sh Hack
	cd ..
	rm -rf ./nerd-fonts
}
################################################################################

# Installer 
install() {
	IFS=';'

	for i in ${@}; do
		pacman -S $i
	done
}

if [ ! -z $(command -v pacman) ]; then
       	primary="git;base-devel;man-pages;wget;bash-completion;udisks2"
	fonts="ttf-dejavu;ttf-inconsolata;ttf-overpass;ttf-crosscore;ttf-joypixels;noto-fonts"
	X="xclip;xcompmgr;xdotool;xwallpaper;sxiv"
	shell="zsh;dash;shellcheck"
	wifi="wireless_tools"
	networking="traceroute;gnu-netcat;nmap;whois"
	editors="vi;vim;neovim"
	python="python2;python2-pip;python3;python-pip"
	other_languages="lua;ruby;perl"
	workflow="tmux"
	math="octave;r;qalculate"
	media="scrot;ffmpeg;alsa-utils;mpv;mpd;mpc;ncmpcpp"
	image_editors="gimp;inkscape"
	reader="zathura;zathura-pdf-mupdf;zathura-pdf-poppler"
	others="light;calcurse;dunst;newsboat;sysstat;perl-image-exiftool;klavaro;python-pywal"
elif [ ! -z $(command -v apt) ]; then
	echo Not done yet ; exit
       	primary="git;build-essential;manpages;manpages-dev;wget;bash-completion"
	#fonts="ttf-dejavu;fonts-inconsolata;ttf-overpass;fonts-croscore;fonts-noto-core"
	#X="xclip;xcompmgr;xdotool;"
	#editors="vi;vim;neovim"
	#python="python2;python2-pip;python3;python-pip"
	#other_languages="lua;ruby;perl"
	#math="octave;r;qalculate"
	#media="scrot;ffmpeg;alsa-utils;mpv"
	#others="light;calcurse;dunst;newsboat;sysstat;perl-image-exiftool;klavaro"
else
	echo "Using other package manager other than 'pacman' or 'apt'"
fi

suckless
install $primary
install $fonts
install $X
install $shell
install $wifi
install $editors
install $workflow
install $reader
install $python
install $other_languages
install $math
install $media
install $image_editors
install $others
nerdfonts
