#!/bin/sh

pacman -Qi | sed 's/Name.*: \(.*\)/\10:0:0/' | sed 's/Install Date.*: \(.*\)/\1\\/;/Date.*/d;/.*[0-9]*:[0-9]*:[0-9]*.*/!d;s/\(.*\)0:0:0/\1|/;s/\(.*\) -03/\1/' | tr -d '\n' | tr '\\' '\n' | awk -F '|' '{cmd="date \"+%s\" -d \""$2"\""; cmd | getline unix_date; close(cmd); printf unix_date; print " ["$1"] -> "$2}' | sort -k 1
