#!/bin/sh

action() {
	dunstify -t 0 --action="clip,Clipboard" --action="file,File" "Save"
}

prnt=$(dunstify -t 0 --action="sel,Selection" --action="focus,Focused window" --action="whole,Whole screen" "Print screen")
case $prnt in
	sel)
		case $(action) in
			clip)
				scrot -s -e "xclip -selection clipboard -t image/png -i \$f; rm \$f;"
				;;
			file)
				scrot -s -e "mv \$f $SCREENSHOTS_PATH/\$f;"
				;;
		esac
		;;
	focus)
		case $(action) in
			clip)
				scrot -u -e "xclip -selection clipboard -t image/png -i \$f; rm \$f;"
				;;
			file)
				scrot -u -e "mv \$f $SCREENSHOTS_PATH/\$f;"
				;;
		esac
		;;
	whole)
		case $(action) in
			clip)
				scrot -e "xclip -selection clipboard -t image/png -i \$f; rm \$f;"
				;;
			file)
				scrot -e "mv \$f $SCREENSHOTS_PATH/\$f;"
				;;
		esac
		;;
esac
