#!/bin/sh
#
# A script to dismount mounted partitions

PADDING=$(lsblk -rn --paths -o NAME,MOUNTPOINT | awk '{ printf "%s\n", length($1)+2 }' | sort -r -n | head -1)
# length($1)+2 for the characters '[' and ']' in the printf below

mntd=$(lsblk -rn --paths -o NAME,MOUNTPOINT |
	while IFS= read -r line;
	do
		set -- $line
		[ -n "$2" ] && printf "%-*s -> %s\n" $PADDING "[$1]" "$2"
	done | dmenu -p "Dismount a partition" -l 20)

[ -n "$mntd" ] && sudo umount "$(echo "$mntd" | sed 's/.*\[\(.*\)\].*/\1/')"
