#!/bin/sh

# My personal runner script for pywal
# This script run pywal on the given image file
# If no file given, restore the last colorscheme
# After running pywal, it sends a xrdb signal to dwm

# Require: pywal; dwm fsignal patch with xrdb

[ -f "$1" ] && wal -s -n -t -i $(readlink -f "$1") > /dev/null 2>&1 || wal -R ; xsetroot -name "fsignal:xrdb"
